---

- name: "Add variables"
  include_vars:
    file: "{{ playbook_dir }}/roles/kafka/defaults/kafka.service.yml"

- name: 'Install kafka'
  include_tasks:
    file: 'install_kafka_2_1.yml'
  when: goal in ['kafka_2_1']

- name: "Stop kafka"
  include_tasks: stop_kafka.yml
  when: goal in ['stop_kafka', 'critical_stop']

- name: 'Deploy producers'
  include_tasks:
    file: 'deploy_producers.yml'
  when: goal in ['deploy_producers'] and (producers_count | int) != 0

