---
kafka_arch_dir: '/tmp/{{ kafka.versions[kafka_version].arch_dir }}'
kafka_arch_url: '{{ kafka.versions[kafka_version].arch_url }}'

kafka_data_dir: '{{ kafka.conf.data_dir }}'
kafka_dist_dir: '{{ kafka.conf.dist_dir }}'

kafka_backup_conf_dir: '{{ kafka.conf.backup_dir }}/conf'
kafka_backup_data_dir: '{{ kafka.conf.backup_dir }}/data'

kafka_server_stop: '{{ kafka_dist_dir }}/bin/kafka-server-stop.sh'
kafka_server_start: '{{ kafka_dist_dir }}/bin/kafka-server-start.sh'

kafka_broker_config_dir: '{{ kafka_dist_dir }}/config'
ansible_broker_config_dir: 'environments/{{ stand }}/kafka/broker_conf'

broker_config_files:
  - consumer.properties
  - log4j.properties
  - producer.properties
  - server.properties
  - tools-log4j.properties
  - trogdor.properties
  - zookeeper.properties
  - connect-console-sink.properties
  - connect-console-source.properties
  - connect-distributed.properties
  - connect-file-sink.properties
  - connect-file-source.properties
  - connect-log4j.properties
  - connect-mirror-maker.properties
  - connect-standalone.properties
  - kraft/broker.properties
  - kraft/controller.properties
  - kraft/server.properties
