
etc_hosts_path: 'etc/host'

zk_name: 'zookeeper'

zk_service: 'zookeeper.service'
zk_service_path: '/etc/systemd/system'

zk_conf: 'zoo.cfg'
zk_conf_path: 'opt/bitnami/zookeeper/conf'

zk_data_path: 'bitnami/zookeeper/data'

delay_between_nodes: 3

docker:
  image:
    name: 'bitnami/zookeeper'
    tag: '3.9'
  network_name: 'host'

zk_servers:
  - "node1"
  - "node2"
  - "node3"
