zk_args:
  memmory: '{{ zk_memmory }}'
  memmory_swap: '{{ zk_swap }}'
  volumes:
    zk_data_dir: '{{ zk_data_dir }}:{{ zk_data_dir }}'
    zk_log_dir: '{{ zk_log_dir }}:{{ zk_log_dir }}'
    zk_conf_dir: '{{ zk_data_dir }}/{{ zk_properties }}:{{ confluent_templates_dir }}/{{ zk_properties }}.template'
    etc_host_path: '{{ etc_hosts_path }}:{{ etc_hosts_path }}'
  flags:
    ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: 'INFO'
    ZOOKEEPER_CLIENT_PORT: '{{ zk_client_port }}'
    ZOOKEEPER_SERVER_ID: "{{ inventory_hostname | regex_replace('node', '') }}"
    KAFKA_OPTS: '"{{ a }} {{ b }} {{ c }} {{ d }} {{ e }} {{ f }} {{ g }} {{ h }} {{ m }} {{ n }}"'

  container_name: '{{ zk_name }}'
  network_mode: '{{ docker.network_mode }}'
  image_path: '{{ docker.image.name }}:{{ docker.image.tag }}'

