---
- name: "Add variables"
  include_vars:
    file: "{{ playbook_dir }}/roles/zookeeper/defaults/zookeeper.service.yml"

- name: "Install zookeeper"
  include_tasks: install_zookeeper.yml
  when: goal in ['install_zookeeper']

- name: "Stop zookeeper"
  include_tasks: stop_zookeeper.yml
  when: goal in ['stop_zookeeper', 'critical_stop']


