---
- name: Setup distributive directory
  shell: |
    rm -rf {{ zookeper_dist_dir }}
    mv {{ zookeeper_arch_dir }} {{ zookeper_dist_dir }}

- name: Create data directory
  file:
    path: "{{ zookeper_data_dir }}"
    state: directory

- name: Create myid file
  copy:
    dest: "{{ zookeper_data_dir }}/myid"
    content: |
      {{ machines[machine].id }}

- name: Setup Config File zoo.cfg
  copy:
    content: "{{ lookup('file', '{{ zoo_cfg_path }}') }}\n"
    dest: "{{ zookeeper.conf.dist_dir }}/conf/zoo.cfg"

- name: Update "{{ zookeper_dist_dir }}/conf/zoo.cfg"
  shell: |
    echo 'server.{{ machines[item].id }}={{ "0.0.0.0" if item == machine else machines[item].ip }}:{{ zookeeper_first_port}}:{{ zookeeper_lead_port }}' >> {{ zookeper_dist_dir }}/conf/zoo.cfg
  loop: "{{ list_machines }}"
