---

- name: 'Remove everything with zookeeper'
  block:
  - name: 'Stop .service'
    systemd_service:
      state: stopped
      name: '{{ zk_service }}'

  - name: 'Stop zookeeper_exporter'
    community.docker.docker_container:
      name: '{{ zk_exp_name }}'
      state: absent
  
  - name: 'Delete directories'
    file:
      path: '{{ item }}'
      state: absent
    loop:
      - '/var/lib/zookeeper'
