- name: Test variables
  debug:
    msg: "{{ docker_arguments }}"

- name: Test create zookeeper.service
  copy:
    dest: "/zookeeper.service"
    content: |
      {{ lookup('template', 'templates/zookeeper.service.j2') }}
