---
- name: Remove .bashrc
  shell: |
    rm -rf /home/{{ machines[machine].username }}/.bashrc

- name: Setup .bashrc file
  copy:
    content: "{{ lookup('template', 'templates/env_setup/bashrc') }}"
    dest: "/home/{{ machines[machine].username }}/.bashrc"

- name: Source .bashrc
  shell: |
    source /home/{{ machines[machine].username }}/.bashrc
