kafka_args:
  container_name: '{{ kafka.docker.container_name }}'
  memory: '{{ kafka.memory }}'
  swap: '{{ kafka.swap }}'
  volumes:
    kafka_log_path: '{{ kafka.log_path }}:{{ kafka.log_path }}'
    etc_hosts: '{{ etc_hosts_path }}:{{ etc_hosts_path }}'
    jaas_config: '{{ kafka.jaas_config.path }}/{{ kafka.jaas_config.name }}:{{ kafka.jaas_config.path }}/{{ kafka.jaas_config.name }}'
  flags:
    CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    KAFKA_BROKER_ID: "{{ kafka.broker_id }}"
    KAFKA_LOG_DIRS: '{{ kafka.log_path }}'
    KAFKA_LISTENERS: '{{ kafka.listeners }}'
    KAFKA_ADVERTISED_LISTENERS: '{{ kafka.advertised_listeners }}'
    KAFKA_ZOOKEEPER_CONNECT: '{{ kafka.zookeeper_connect }}'
    KAFKA_SECURITY_INTER_BROKER_PROTOCOL: '{{ kafka.flags.security_inter_broker_protocol }}'
    KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: '{{ kafka.flags.sasl_mechanism_inter_broker_protocol }}'
    KAFKA_SASL_ENABLED_MECHANISMS: '{{ kafka.flags.sasl_enabled_mechanisms }}'
    KAFKA_AUTHORIZER_CLASS_NAME: '{{ kafka.flags.authorizer_class_name }}'
    KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: '{{ kafka.flags.allow_everyone_if_no_acl_found }}'
    KAFKA_SUPER_USERS: '{{ kafka.flags.super_users }}'
    KAFKA_OPTS: '"-Djava.security.auth.login.config={{ kafka.jaas_config.path }}/{{ kafka.jaas_config.name }}"'
  network_mode: '{{ kafka.docker.network_mode }}'
  image:
    path: '{{ kafka.docker.image.path }}'
    version: '{{ kafka.docker.image.version }}'
  ports:
    sasl:
      outside: '{{ kafka.ports.sasl.outside }}'
      inside: '{{ kafka.ports.sasl.inside }}'
    monitoring:
      outside: '{{ kafka.ports.monitoring.outside }}'
      inside: '{{ kafka.ports.monitoring.inside }}'
