---
packages:
  jdk:
    fedora: java-17-openjdk.x86_64
    path: /usr/lib/jvm/java-17-openjdk-17.0.5.0.8-2.fc35.x86_64/bin/java

archives:
  zookeeper:
    url: https://dlcdn.apache.org/zookeeper/zookeeper-3.8.4/apache-zookeeper-3.8.4-bin.tar.gz
    archdir: apache-zookeeper-3.8.4-bin

zookeeper:
  conf:
    tick_time: 2000
    init_time: 20
    sync_limit: 5
    client_port: 2181
    data_dir: /var/lib/zookeeper
    ports:
      client: 2181
      first: 2888
      lead: 3888
  vm1:
    ip: "{{ vm1_ip }}"
  vm2:
    ip: "{{ vm2_ip }}"
  vm3:
    ip: "{{ vm3_ip }}"
