---
- name: "Main kafkaBox playbook"
  hosts: all
  serial: 1
  tasks:
  - name: "Common tasks"
    include_role:
      name: common
    when: goal in ['init_host', 'install_monitoring']
  
  - name: "Zookeeper tasks"
    include_role:
      name: zookeeper
    when: goal in ['install_zookeeper', 'stop_zookeeper', 'critical_stop']

  - name: "Kafka tasks"
    include_role:
      name: kafka
    when: goal in ['kafka_2_1', 'deploy_producers', 'stop_kafka', 'stop_ksm', 'install_ksm', 'critical_stop']
