---
- name: KafkaBox
  hosts: "{{ machine }}"
  become: true
  backup: yes
  tasks:
    - name: Kafka prepare
      import_tasks: prepare.yml
      backup: yes
    - name: Set Up Environment
      include_role:
        name: env_setup
      when: task == "env_setup"

    - name: Set Up ZooKeeper
      include_role:
        name: zookeeper
      when: task == "zookeeper"

    - name: Set Up Kafka
      include_role:
        name: kafka
      when: task == "kafka"
