---
- name: Setup the Kafka
  hosts: "{{ machine }}"
  become: true
  tasks:
    - name: Set Up Environment
      include_role:
        name: env_setup
      when: task == "env_setup"

    - name: Set Up Environment
      include_role:
        name: zookeeper
      when: task == "zookeeper"
