all:
  hosts:
    node1:
      ansible_host: node1
      ansible_user: root
    node2:
      ansible_host: node2
      ansible_user: root
    node3:
      ansible_host: node3
      ansible_user: root
    node4:
      ansible_host: node4
      ansible_user: root

  children:
    zookeeper:
      hosts:
        node1:
        node2:
        node3:
    monitoring:
      hosts:
        node4:
